[dependencies]
base = "0.11.0"
nacdb = "0.10.15"
stable-buffer = "https://github.com/canscale/StableBuffer#v1.3.0"
map7 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0@f0e25632e5da80118274e78ceeb5bec95f3c2b81"
stableheapbtreemap = "1.3.0"
itertools = "0.1.2"
xtended-numbers = "0.2.1"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#master"
candb = "1.0.2"
prng = "0.0.3"

[package]
name = "nacdb-reorder"
version = "2.0.1"
description = "Reorderable lists in NacDB database"
repository = "https://github.com/vporton/NacDBReorder"
keywords = [ "database", "databases", "order", "reorder", "nacdb" ]
license = "MIT"